name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: make build
      
    - name: Build ExtJS application
      run: make prod
      
    # - name: Prepare docs directory
    #   run: |
    #     # Создаем папку docs если её нет
    #     mkdir -p docs
    #     # Очищаем содержимое docs
    #     rm -rf docs/*
        
    # - name: Copy production build to docs
    #   run: |
    #     # Копируем все файлы из production сборки в docs
    #     cp -r build/production/JsonViewer/* docs/
        
    # - name: Create .nojekyll file
    #   run: |
    #     # Создаем файл для отключения Jekyll на GitHub Pages
    #     touch docs/.nojekyll
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Auto-build: Update docs for GitHub Pages" || exit 0
        git push
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
