name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: make build
      
    - name: Build ExtJS application
      run: make prod

    - name: Update repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto build"
        branch: master
        #file_pattern: build/production/JsonViewer
